-- Tabela de Categoria
CREATE TABLE public.tb_categoria (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome varchar(100) NOT NULL,
	descricao TEXT NULL,
	area varchar(100) NULL,
	cor_hex varchar(7) NULL,
	CONSTRAINT tb_categoria_pkey PRIMARY KEY (id),
	CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

-- Tabela de Editora
CREATE TABLE public.tb_editora (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome varchar(100) NOT NULL,
	cnpj varchar(18) NULL,
	cidade varchar(100) NULL,
	email_contato varchar(100) NULL,
	CONSTRAINT tb_editora_pkey PRIMARY KEY (id),
	CONSTRAINT uk_editora_nome UNIQUE (nome),
	CONSTRAINT uk_editora_cnpj UNIQUE (cnpj)
);

-- Tabela de Livro
CREATE TABLE public.tb_livro (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo varchar(255) NOT NULL,
	isbn varchar(13) NULL,
	ano_publicacao int4 NULL,
	num_paginas int4 NULL,
	sinopse TEXT NULL,
	categoria_id int8 NOT NULL,
	editora_id int8 NOT NULL,
	CONSTRAINT tb_livro_pkey PRIMARY KEY (id),
	CONSTRAINT uk_livro_isbn UNIQUE (isbn),
	CONSTRAINT fk_livro_categoria FOREIGN KEY (categoria_id) REFERENCES public.tb_categoria(id),
	CONSTRAINT fk_livro_editora FOREIGN KEY (editora_id) REFERENCES public.tb_editora(id)
);

-- Tabela de junção Livro & Autor (muitos para muitos)
CREATE TABLE public.tb_livro_autor (
	livro_id int8 NOT NULL,
	autor_id int8 NOT NULL,
	CONSTRAINT tb_livro_autor_pkey PRIMARY KEY (livro_id, autor_id),
	CONSTRAINT fk_livro_autor_livro FOREIGN KEY (livro_id) REFERENCES public.tb_livro(id),
	CONSTRAINT fk_livro_autor_autor FOREIGN KEY (autor_id) REFERENCES public.tb_autor(id)
);

-- Tabela de Comentario
CREATE TABLE public.tb_comentario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo varchar(255) NULL,
	texto TEXT NOT NULL,
	nota int4 NULL,
	data_postagem date NULL,
	livro_id int8 NOT NULL,
	user_id int8 NOT NULL,
	CONSTRAINT tb_comentario_pkey PRIMARY KEY (id),
	CONSTRAINT fk_comentario_livro FOREIGN KEY (livro_id) REFERENCES public.tb_livro(id),
	CONSTRAINT fk_comentario_user FOREIGN KEY (user_id) REFERENCES public.tb_user(id)
);